import { Category } from '@/lib/types';

export const CATEGORIES: Category[] = [
  {
    slug: 'action',
    name: 'Action',
    icon: '⚡',
    color: { bg: 'oklch(94% 0.04 18)', text: 'oklch(36% 0.16 18)' },
    description: 'Fast-paced action games that test your reflexes.',
  },
  {
    slug: 'puzzle',
    name: 'Puzzle',
    icon: '🧩',
    color: { bg: 'oklch(93% 0.04 258)', text: 'oklch(36% 0.14 258)' },
    description: 'Brain-teasing puzzles and logic challenges.',
  },
  {
    slug: 'racing',
    name: 'Racing',
    icon: '🏎️',
    color: { bg: 'oklch(95% 0.06 80)', text: 'oklch(38% 0.16 80)' },
    description: 'Speed, drift, and compete on epic tracks.',
  },
  {
    slug: 'sports',
    name: 'Sports',
    icon: '⚽',
    color: { bg: 'oklch(93% 0.05 148)', text: 'oklch(36% 0.16 148)' },
    description: 'Football, basketball, golf, and more.',
  },
  {
    slug: 'io',
    name: 'IO',
    icon: '🌐',
    color: { bg: 'oklch(93% 0.04 192)', text: 'oklch(36% 0.12 192)' },
    description: 'Multiplayer .io games for everyone.',
  },
  {
    slug: 'casual',
    name: 'Casual',
    icon: '🎮',
    color: { bg: 'oklch(94% 0.04 352)', text: 'oklch(38% 0.14 352)' },
    description: 'Easy to pick up, hard to put down.',
  },
  {
    slug: 'shooting',
    name: 'Shooting',
    icon: '🎯',
    color: { bg: 'oklch(94% 0.05 55)', text: 'oklch(38% 0.16 55)' },
    description: 'Aim, shoot, and survive the action.',
  },
  {
    slug: 'adventure',
    name: 'Adventure',
    icon: '🗺️',
    color: { bg: 'oklch(93% 0.05 162)', text: 'oklch(36% 0.15 162)' },
    description: 'Explore vast worlds and epic journeys.',
  },
  {
    slug: 'skill',
    name: 'Skill',
    icon: '🏆',
    color: { bg: 'oklch(95% 0.055 72)', text: 'oklch(38% 0.17 72)' },
    description: 'Master these games with practice and skill.',
  },
  {
    slug: 'arcade',
    name: 'Arcade',
    icon: '🕹️',
    color: { bg: 'oklch(93% 0.04 238)', text: 'oklch(36% 0.13 238)' },
    description: 'Classic arcade-style fun.',
  },
  {
    slug: 'strategy',
    name: 'Strategy',
    icon: '♟️',
    color: { bg: 'oklch(93% 0.02 228)', text: 'oklch(36% 0.1 228)' },
    description: 'Think before you act and outsmart the enemy.',
  },
  {
    slug: 'girls',
    name: 'Girls',
    icon: '💅',
    color: { bg: 'oklch(94% 0.04 6)', text: 'oklch(38% 0.15 6)' },
    description: 'Fashion, makeup, cooking, and more.',
  },
  {
    slug: 'multiplayer',
    name: 'Multiplayer',
    icon: '👥',
    color: { bg: 'oklch(93% 0.04 280)', text: 'oklch(36% 0.14 280)' },
    description: 'Play online with players from around the world.',
  },
  {
    slug: '3d',
    name: '3D',
    icon: '📦',
    color: { bg: 'oklch(94% 0.04 210)', text: 'oklch(36% 0.13 210)' },
    description: 'Immersive 3D games with amazing graphics.',
  },
  {
    slug: 'car',
    name: 'Car',
    icon: '🚗',
    color: { bg: 'oklch(94% 0.05 40)', text: 'oklch(38% 0.16 40)' },
    description: 'Drive, drift, and race with fast cars.',
  },
  {
    slug: 'clicker',
    name: 'Clicker',
    icon: '🖱️',
    color: { bg: 'oklch(95% 0.05 90)', text: 'oklch(38% 0.15 90)' },
    description: 'Idle games, clickers, and incremental upgrades.',
  },
  {
    slug: 'cooking',
    name: 'Cooking',
    icon: '🍳',
    color: { bg: 'oklch(94% 0.05 120)', text: 'oklch(36% 0.15 120)' },
    description: 'Bake, cook, and manage your own kitchen.',
  },
  {
    slug: 'stickman',
    name: 'Stickman',
    icon: '🧍',
    color: { bg: 'oklch(93% 0.01 240)', text: 'oklch(36% 0.05 240)' },
    description: 'Epic physics battles and adventures featuring stickmen.',
  },
  {
    slug: 'fighting',
    name: 'Fighting',
    icon: '🥊',
    color: { bg: 'oklch(94% 0.05 22)', text: 'oklch(36% 0.17 22)' },
    description: 'One-on-one combat and brawler games.',
  },
  {
    slug: 'running',
    name: 'Running',
    icon: '🏃',
    color: { bg: 'oklch(94% 0.05 140)', text: 'oklch(36% 0.15 140)' },
    description: 'Endless runners and speed-based challenges.',
  },
  {
    slug: 'hypercasual',
    name: 'Hypercasual',
    icon: '⚡',
    color: { bg: 'oklch(95% 0.05 62)', text: 'oklch(38% 0.16 62)' },
    description: 'Simple one-tap games with addictive loops.',
  },
  {
    slug: 'zombie',
    name: 'Zombie',
    icon: '🧟',
    color: { bg: 'oklch(92% 0.04 130)', text: 'oklch(34% 0.14 130)' },
    description: 'Survive waves of zombies and undead enemies.',
  },
  {
    slug: 'beauty',
    name: 'Beauty',
    icon: '💄',
    color: { bg: 'oklch(94% 0.04 352)', text: 'oklch(38% 0.15 352)' },
    description: 'Makeover, makeup, and beauty salon games.',
  },
  {
    slug: 'simulation',
    name: 'Simulation',
    icon: '🏙️',
    color: { bg: 'oklch(93% 0.03 220)', text: 'oklch(36% 0.12 220)' },
    description: 'Manage, build, and simulate real-life scenarios.',
  },
  {
    slug: 'kids',
    name: 'Kids',
    icon: '🎈',
    color: { bg: 'oklch(95% 0.05 80)', text: 'oklch(38% 0.16 80)' },
    description: 'Fun and safe games for young players.',
  },
  {
    slug: 'soccer',
    name: 'Soccer',
    icon: '⚽',
    color: { bg: 'oklch(93% 0.05 148)', text: 'oklch(36% 0.16 148)' },
    description: 'Score goals and win matches on the pitch.',
  },
  {
    slug: '2player',
    name: '2 Player',
    icon: '👫',
    color: { bg: 'oklch(93% 0.04 280)', text: 'oklch(36% 0.14 280)' },
    description: 'Play with a friend on the same screen.',
  },
  {
    slug: 'platformer',
    name: 'Platformer',
    icon: '🍄',
    color: { bg: 'oklch(94% 0.05 60)', text: 'oklch(38% 0.16 60)' },
    description: 'Jump, run, and explore side-scrolling worlds.',
  },
  {
    slug: 'horror',
    name: 'Horror',
    icon: '👻',
    color: { bg: 'oklch(91% 0.02 270)', text: 'oklch(32% 0.1 270)' },
    description: 'Scary games and thrilling survival experiences.',
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}
